# Generated by Django 4.2.13 on 2024-05-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterLevel', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.waterleveldevice')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.temperatureandhumiditydevice')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.soilmoisturedevice')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
        migrations.CreateModel(
            name='LightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.temperatureandhumiditydevice')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
    ]
