# Generated by Django 4.2.13 on 2024-05-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('wifi_enabled', models.BooleanField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('serial_enabled', models.BooleanField(null=True)),
                ('serial_port', models.CharField(max_length=200, null=True)),
                ('serial_baudrate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('i2c_enabled', models.BooleanField(null=True)),
                ('i2c_address', models.IntegerField(null=True)),
                ('gpio_enabled', models.BooleanField(null=True)),
                ('gpio_pin', models.IntegerField(null=True)),
                ('connectedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureAndHumidityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('i2c_enabled', models.BooleanField(null=True)),
                ('i2c_address', models.IntegerField(null=True)),
                ('spi_enabled', models.BooleanField(null=True)),
                ('spi_address', models.IntegerField(null=True)),
                ('gpio_enabled', models.BooleanField(null=True)),
                ('gpio_pin', models.IntegerField(null=True)),
                ('connectedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('i2c_enabled', models.BooleanField(null=True)),
                ('i2c_address', models.IntegerField(null=True)),
                ('gpio_enabled', models.BooleanField(null=True)),
                ('gpio_pin', models.IntegerField(null=True)),
                ('connectedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.reporterdevice')),
            ],
        ),
    ]
