# Generated by Django 4.2.13 on 2024-05-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporterdevice',
            name='serial_baudrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporterdevice',
            name='serial_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporterdevice',
            name='serial_port',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reporterdevice',
            name='wifi_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisturedevice',
            name='gpio_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisturedevice',
            name='gpio_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisturedevice',
            name='i2c_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilmoisturedevice',
            name='i2c_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureandhumiditydevice',
            name='gpio_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureandhumiditydevice',
            name='gpio_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureandhumiditydevice',
            name='i2c_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureandhumiditydevice',
            name='i2c_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureandhumiditydevice',
            name='spi_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureandhumiditydevice',
            name='spi_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterleveldevice',
            name='gpio_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterleveldevice',
            name='gpio_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterleveldevice',
            name='i2c_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterleveldevice',
            name='i2c_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
