# Generated by Django 4.2.13 on 2024-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_reporterdevice_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
